version: "3"
services:
    frontend:
        container_name: api_client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
        tty: true
    backend:
        container_name: api_server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./server:/usr/src/app
        links:
            - "db:redis"      
    db:
        image: redis
        ports:
            - "6379:6379"